USE [master]
GO
/****** Object:  Database [ensek]    Script Date: 19/08/2022 18:44:23 ******/
CREATE DATABASE [ensek]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ensek', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ensek.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ensek_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ensek_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ensek] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ensek].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ensek] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ensek] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ensek] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ensek] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ensek] SET ARITHABORT OFF 
GO
ALTER DATABASE [ensek] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ensek] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ensek] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ensek] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ensek] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ensek] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ensek] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ensek] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ensek] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ensek] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ensek] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ensek] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ensek] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ensek] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ensek] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ensek] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ensek] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ensek] SET RECOVERY FULL 
GO
ALTER DATABASE [ensek] SET  MULTI_USER 
GO
ALTER DATABASE [ensek] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ensek] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ensek] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ensek] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ensek] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ensek] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ensek', N'ON'
GO
ALTER DATABASE [ensek] SET QUERY_STORE = OFF
GO
USE [ensek]
GO
/****** Object:  Table [dbo].[Accounts]    Script Date: 19/08/2022 18:44:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[id] [bigint] NOT NULL,
	[firstname] [varchar](200) NOT NULL,
	[lastname] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MeterReadings]    Script Date: 19/08/2022 18:44:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MeterReadings](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[accountId] [bigint] NOT NULL,
	[reading] [varchar](50) NOT NULL,
	[readingDate] [datetime] NOT NULL,
	[createdDate] [datetime] NOT NULL,
 CONSTRAINT [PK_MeterReadings] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MeterReadings] ADD  CONSTRAINT [DF_MeterReadings_createdDate]  DEFAULT (getdate()) FOR [createdDate]
GO
/****** Object:  StoredProcedure [dbo].[InsertMeterReadings]    Script Date: 19/08/2022 18:44:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[InsertMeterReadings]
@accountId bigint,
@reading varchar(50),
@readingDate datetime
AS
BEGIN
	IF EXISTS(
		SELECT *
		FROM [Accounts] WITH (NOLOCK)
		WHERE id = @accountId
	)
	BEGIN
		IF NOT EXISTS(
			SELECT * 
			FROM [dbo].MeterReadings WITH (NOLOCK)
			WHERE accountId = @accountId
			AND reading = @reading 
		) 
		BEGIN
			INSERT INTO [dbo].MeterReadings(
			accountId,
			reading,
			readingDate
			)
			VALUES(
			@accountId,
			@reading,
			@readingDate
			)

			SELECT 'Account Updated Successfully.'
		END
		ELSE
		BEGIN
			SELECT 'Reading Already Exists'
		END
	END
	ELSE
	BEGIN
		SELECT 'Invalid Account.'
	END
END

GO
USE [master]
GO
ALTER DATABASE [ensek] SET  READ_WRITE 
GO
